### ISSUE TITLE
Node version requirements

### ISSUE THREAD

**Issue by jamesmacwhite** [ashleighsims/nct-buses-nodejs#2]
I had an older version of node 10.x LTS and the BusTimes function kept failing with a syntax error. It's due to having an older version of nodejs with arrow functions in exported classes

```
isLate = (aimedArrival, expectedArrival) => {
         ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/mnt/d/Projects/nct-buses-nodejs/BusTimes.js:3:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

**Comment by ashleighsims** [comment]
@jamesmacwhite I’ve added the “engines” object to the package.json now.

**Comment by jamesmacwhite** [comment]
@ashleighsims Nice!
